spring:

  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customers/**
              filters:
                - AddRequestHeader=X-System-Name, Api-Gateway-System
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8080

